/**
 * Application Routes
 * Generated by @exeris/codegen-ts
 */

import { Routes } from '@angular/router';
import { notFoundRoutes } from './generated/src/app/pages/not-found.route';

export const routes: Routes = [
  {
    path: '',
    redirectTo: '404',
    pathMatch: 'full'
  },
  ...notFoundRoutes,
];
