/**
 * Angular Application Configuration
 * Generated by @exeris/codegen-ts
 * 
 * Uses Angular 22 Zoneless mode with Signals
 */

import { ApplicationConfig, provideZonelessChangeDetection } from '@angular/core';
import { provideRouter, withComponentInputBinding } from '@angular/router';
import { provideClientHydration } from '@angular/platform-browser';

import { routes } from './app.routes';

export const appConfig: ApplicationConfig = {
  providers: [
    // Zoneless mode - no zone.js needed for change detection
    provideZonelessChangeDetection(),
    provideRouter(routes, withComponentInputBinding()),
    provideClientHydration(),
    // Row enter/leave animations are native (animate.enter, Angular 22) — a
    // compiler feature, so no @angular/animations package or provider is needed.
  ],
};
